package com.problems.string;

/*
    You are given two strings s and t.
    String t is generated by random shuffling string s and then add one more letter at a random position.
    Return the letter that was added to t.

    Input: s = "abcd", t = "abcde"
    Output: "e"
    Explanation: 'e' is the letter that was added.

    Input: s = "", t = "y"
    Output: "y"
 */
public class DifferenceInTwoString {
    public char findTheDifference(String s, String t) {
        int total = 0;
        for (int i=0;i<t.length();i++){
            total = total + t.charAt(i);
        }
        for (int i = 0; i < s.length(); i++) {
            total = total - s.charAt(i);
        }
        return (char) total;
    }

    public static void main(String[] args) {
        DifferenceInTwoString ob = new DifferenceInTwoString();
        String s = "abcd";
        String t = "abcde";
        System.out.println("The letter is '"+ob.findTheDifference(s,t)+"'.");
    }
}
